# -*- coding: utf-8 -*-
"""defect pre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJcHrsqydRb8_y1fjpZ6Txg1OjeNWsDj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

import os
!pip install streamlit
import streamlit as st

st.write("Current directory:", os.getcwd())
st.write("Files in directory:", os.listdir())

df = pd.read_csv("defects_data.csv")
data = {
    'temperature': [55, 60, 45, 70, 65, 40, 50, 80, 75, 38],
    'pressure': [20, 22, 18, 30, 25, 17, 19, 35, 33, 16],
    'speed': [300, 320, 280, 350, 330, 270, 290, 360, 340, 260],
    'defect': [0, 0, 1, 0, 0, 1, 0, 1, 1, 1]   # 1 = defective, 0 = good
}

df = pd.DataFrame(data)

X = df[['temperature', 'pressure', 'speed']]
y = df['defect']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

new_product = [[72, 28, 340]]  # sample input: temperature, pressure, speed

prediction = model.predict(new_product)

print("\nNew Product Defect Prediction:")
print("Defective" if prediction[0] == 1 else "Good")

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.scatter(range(len(y_test)), y_test, label="Actual Price")
plt.scatter(range(len(y_pred)), y_pred, label="Predicted Price")
plt.xlabel("Sample")
plt.ylabel("Price")
plt.title("Actual vs Predicted Mobile Price")
plt.legend()
plt.show()

import pickle

with open("defect_pre.pkl", "wb") as file:
    pickle.dump(model, file)

from google.colab import files
files.download('defect_pre.pkl')

import sklearn
print(sklearn.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# scikit-learn
# pandas
# numpy
# matplotlib
# seaborn
# joblib

ls

from google.colab import files
files.download("requirements.txt")