# -*- coding: utf-8 -*-
"""salaryPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPzZRYU2_p_W1CpimDKgedK7gSEWr8sh
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

saldf = pd.read_csv('/content/Salary Data.csv')

saldf.head()

saldf.info()

saldf_cleaned = saldf.dropna(subset=['Years of Experience', 'Salary'])
inp = saldf_cleaned[['Years of Experience']]
out = saldf_cleaned['Salary']

LR = LinearRegression()

LR.fit(inp,out)

LR.predict([[5]])

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# 'inp' (Years of Experience) and 'out' (Salary) are defined in previous cells
X_train, X_test, y_train, y_test = train_test_split(inp, out, test_size=0.2, random_state=42)

# Create a new Linear Regression model instance for plotting to avoid affecting the globally defined 'LR'
LR_plot = LinearRegression()
LR_plot.fit(X_train, y_train)

# Make predictions on the test set
y_pred = LR_plot.predict(X_test)

plt.figure(figsize=(10,6))
plt.scatter(range(len(y_test)), y_test, label="Actual Salary")
plt.scatter(range(len(y_pred)), y_pred, label="Predicted Salary")
plt.xlabel("Sample Index")
plt.ylabel("Salary")
plt.title("Actual vs Predicted Salary")
plt.legend()
plt.show()

import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(LR, file)

from google.colab import files
files.download('model.pkl')

